/**
 * TLS ClientHello parser (alpha.6 §28–§31, §76, §88).
 *
 * §88 requires *real* positive fixtures, and the reason is worth stating: a
 * parser tested only against hand-written bytes is tested against the author's
 * idea of the format, and a parser tested only against malformed input can pass
 * by rejecting everything. So the positive fixture here is generated by Node's
 * own TLS stack — a genuine ClientHello, with the extensions a real client
 * actually sends — captured off a socket. If the parser stops understanding
 * real TLS, this test goes red rather than the enforcement quietly becoming
 * "deny everything", which would look like security and behave like an outage.
 *
 * The negative cases are the ones that matter for §31. Every single one of them
 * must produce a *verdict the caller denies*, and specifically must never
 * produce "no SNI check was possible, carry on".
 */

import { strict as assert } from 'node:assert';
import { describe, it, before } from 'node:test';
import { createServer, type Server } from 'node:net';
// lint-allow no-raw-network: this is a test fixture generator, not kernel egress. It
// connects to a loopback listener in this process to capture a genuine ClientHello,
// which §88 requires the SNI parser to be tested against.
import { connect as tlsConnect } from 'node:tls';

import { MAX_CLIENT_HELLO_BYTES, parseClientHello } from '../../src/security/egress-proxy/tls.ts';

/**
 * Capture a real ClientHello.
 *
 * A plain TCP listener that never answers: the client sends its hello and then
 * waits forever, which is exactly the moment the proxy inspects.
 */
async function captureClientHello(serverName?: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    let server: Server;
    const timer = setTimeout(() => {
      server?.close();
      reject(new Error('no ClientHello arrived'));
    }, 10_000);

    server = createServer((socket) => {
      socket.once('data', (chunk: Buffer) => {
        clearTimeout(timer);
        socket.destroy();
        server.close();
        resolve(chunk);
      });
    });

    server.listen(0, '127.0.0.1', () => {
      const address = server.address();
      const port = typeof address === 'object' && address !== null ? address.port : 0;
      const socket = tlsConnect({
        host: '127.0.0.1',
        port,
        ...(serverName !== undefined ? { servername: serverName } : {}),
        rejectUnauthorized: false,
      });
      // The handshake will never complete; the error is expected and ignored.
      socket.on('error', () => {});
    });
  });
}

describe('TLS ClientHello parsing — positive fixtures', () => {
  let helloWithSni: Buffer;
  let helloWithoutSni: Buffer;

  before(async () => {
    helloWithSni = await captureClientHello('allowed.example');
    // Node omits the SNI extension when the server name is an IP literal,
    // which is the real-world source of the `no-sni` case.
    helloWithoutSni = await captureClientHello();
  });

  it('extracts the server name from a ClientHello a real TLS client produced', () => {
    const result = parseClientHello(helloWithSni);
    assert.equal(result.kind, 'sni');
    assert.equal((result as { serverName: string }).serverName, 'allowed.example');
    assert.equal((result as { encryptedClientHello: boolean }).encryptedClientHello, false);
  });

  it('reports no-sni for a real ClientHello that carries no server name', () => {
    const result = parseClientHello(helloWithoutSni);
    // Either outcome is legitimate depending on how the platform's TLS stack
    // fills in the host; what must never happen is `malformed`, which would mean
    // the parser cannot read real traffic.
    assert.ok(
      result.kind === 'no-sni' || result.kind === 'sni',
      `expected a parseable hello, got ${result.kind}`,
    );
  });

  it('reassembles a ClientHello delivered one byte at a time', () => {
    // Deliberate fragmentation is the cheap way to confuse a parser that assumes
    // one record equals one message. Feeding prefixes proves the incremental
    // path never guesses: every prefix is `incomplete` until the real end.
    let sawSni = false;
    for (let n = 1; n <= helloWithSni.length; n += 1) {
      const result = parseClientHello(helloWithSni.subarray(0, n));
      if (result.kind === 'sni') {
        sawSni = true;
        assert.equal((result as { serverName: string }).serverName, 'allowed.example');
        break;
      }
      assert.equal(result.kind, 'incomplete', `prefix of ${n} bytes returned ${result.kind}`);
    }
    assert.equal(sawSni, true, 'the parser never reached a verdict on a complete hello');
  });
});

describe('TLS ClientHello parsing — fail closed (§31)', () => {
  it('rejects a buffer that is not a TLS record', () => {
    const result = parseClientHello(Buffer.from('GET / HTTP/1.1\r\nHost: x\r\n\r\n'));
    assert.equal(result.kind, 'not-tls');
  });

  it('denies rather than skips when the hello exceeds the parser budget', () => {
    // The single most important test in this file. The tempting implementation
    // of "too big" is to stop parsing and let the connection through, which
    // turns a 16 KB write into an SNI-check bypass.
    const oversized = Buffer.alloc(MAX_CLIENT_HELLO_BYTES + 1);
    oversized[0] = 0x16;
    assert.equal(parseClientHello(oversized).kind, 'too-large');
  });

  it('denies a hello whose declared record length is impossible', () => {
    const buf = Buffer.alloc(64);
    buf[0] = 0x16;
    buf[1] = 0x03;
    buf[2] = 0x01;
    buf.writeUInt16BE(0xffff, 3); // above the 2^14 plaintext maximum
    assert.equal(parseClientHello(buf).kind, 'malformed');
  });

  it('rejects a record whose version is not TLS', () => {
    const buf = Buffer.alloc(64);
    buf[0] = 0x16;
    buf[1] = 0x02;
    buf.writeUInt16BE(16, 3);
    assert.equal(parseClientHello(buf).kind, 'not-tls');
  });

  it('rejects a handshake message that is not a ClientHello', () => {
    const body = Buffer.alloc(8);
    body[0] = 0x02; // ServerHello
    body.writeUIntBE(4, 1, 3);
    assert.equal(parseClientHello(record(body)).kind, 'not-client-hello');
  });

  it('rejects a session id longer than the protocol permits', () => {
    const hello = clientHello({ sessionIdLength: 40 });
    assert.equal(parseClientHello(hello).kind, 'malformed');
  });

  it('rejects an odd-length cipher suite list', () => {
    const hello = clientHello({ cipherSuiteBytes: 3 });
    assert.equal(parseClientHello(hello).kind, 'malformed');
  });

  it('rejects an extension whose length runs past the extension block', () => {
    const extensions = Buffer.alloc(6);
    extensions.writeUInt16BE(0x0000, 0); // server_name
    extensions.writeUInt16BE(0x00ff, 2); // claims 255 bytes; 2 remain
    assert.equal(parseClientHello(clientHello({ extensions })).kind, 'malformed');
  });

  it('rejects two server_name extensions rather than choosing one', () => {
    // §34's rule at the TLS layer: never resolve a contradiction in favour of
    // either side.
    const one = serverNameExtension('allowed.example');
    const two = serverNameExtension('denied.example');
    const result = parseClientHello(clientHello({ extensions: Buffer.concat([one, two]) }));
    assert.equal(result.kind, 'malformed');
  });

  it('rejects an extension block claiming more than 128 extensions', () => {
    const filler: Buffer[] = [];
    for (let i = 0; i < 200; i += 1) {
      const ext = Buffer.alloc(4);
      ext.writeUInt16BE(0x1000 + i, 0);
      ext.writeUInt16BE(0, 2);
      filler.push(ext);
    }
    assert.equal(parseClientHello(clientHello({ extensions: Buffer.concat(filler) })).kind, 'malformed');
  });

  it('reports Encrypted Client Hello so the caller can deny it (§30)', () => {
    const extensions = Buffer.concat([serverNameExtension('public.example'), echExtension()]);
    const result = parseClientHello(clientHello({ extensions }));
    assert.equal(result.kind, 'sni');
    assert.equal((result as { encryptedClientHello: boolean }).encryptedClientHello, true);
  });

  it('finds the server name in a hand-built hello, proving the fixtures agree', () => {
    const result = parseClientHello(clientHello({ extensions: serverNameExtension('registry.npmjs.org') }));
    assert.equal(result.kind, 'sni');
    assert.equal((result as { serverName: string }).serverName, 'registry.npmjs.org');
  });
});

// --- fixture builders ------------------------------------------------------

/** Wrap a handshake body in a TLS record. */
function record(body: Buffer): Buffer {
  const header = Buffer.alloc(5);
  header[0] = 0x16;
  header[1] = 0x03;
  header[2] = 0x01;
  header.writeUInt16BE(body.length, 3);
  return Buffer.concat([header, body]);
}

function clientHello(
  opts: {
    sessionIdLength?: number;
    cipherSuiteBytes?: number;
    extensions?: Buffer;
  } = {},
): Buffer {
  const sessionIdLength = opts.sessionIdLength ?? 0;
  const cipherSuiteBytes = opts.cipherSuiteBytes ?? 2;
  const extensions = opts.extensions;

  const parts: Buffer[] = [];
  parts.push(Buffer.from([0x03, 0x03])); // legacy_version
  parts.push(Buffer.alloc(32)); // random
  parts.push(Buffer.from([sessionIdLength]));
  parts.push(Buffer.alloc(Math.min(sessionIdLength, 32)));
  const suites = Buffer.alloc(2 + cipherSuiteBytes);
  suites.writeUInt16BE(cipherSuiteBytes, 0);
  parts.push(suites);
  parts.push(Buffer.from([0x01, 0x00])); // one compression method: null

  if (extensions !== undefined) {
    const length = Buffer.alloc(2);
    length.writeUInt16BE(extensions.length, 0);
    parts.push(length, extensions);
  }

  const body = Buffer.concat(parts);
  const message = Buffer.alloc(4 + body.length);
  message[0] = 0x01;
  message.writeUIntBE(body.length, 1, 3);
  body.copy(message, 4);
  return record(message);
}

function serverNameExtension(name: string): Buffer {
  const host = Buffer.from(name, 'latin1');
  const entry = Buffer.alloc(3 + host.length);
  entry[0] = 0x00; // host_name
  entry.writeUInt16BE(host.length, 1);
  host.copy(entry, 3);

  const list = Buffer.alloc(2 + entry.length);
  list.writeUInt16BE(entry.length, 0);
  entry.copy(list, 2);

  const ext = Buffer.alloc(4 + list.length);
  ext.writeUInt16BE(0x0000, 0);
  ext.writeUInt16BE(list.length, 2);
  list.copy(ext, 4);
  return ext;
}

function echExtension(): Buffer {
  const ext = Buffer.alloc(6);
  ext.writeUInt16BE(0xfe0d, 0);
  ext.writeUInt16BE(2, 2);
  return ext;
}
